### ISSUE TITLE
Error while running `miracl` CLI: GLIBCXX_3.4.26 not found

### ISSUE THREAD

**Issue by yeunkim** [AICONSlab/MIRACL#94]
Hi,

I've built the Docker version of MIRACL today using the generic/default installation instructions:

```
$ git clone https://www.github.com/mgoubran/MIRACL
$ cd MIRACL
```

After instantiating a container (using `docker compose`), opening up an interactive shell, and calling `miracl`, I get the following error:
```
ImportError: /opt/miniconda/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/miniconda/lib/python3.7/site-packages/SimpleITK/_SimpleITK.so)
```

The full traceback:
```
Traceback (most recent call last):
  File "/opt/miniconda/bin/miracl", line 33, in <module>
    sys.exit(load_entry_point('MIRACL', 'console_scripts', 'miracl')())
  File "/opt/miniconda/bin/miracl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/miniconda/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 207, in load
    module = import_module(match.group('module'))
  File "/opt/miniconda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/miracl/cli.py", line 19, in <module>
    from miracl.connect import cli_connect
  File "/code/miracl/connect/cli_connect.py", line 5, in <module>
    from miracl.connect import miracl_connect_label_graph_proj_dens, miracl_connect_ROI_matrix_connectogram
  File "/code/miracl/connect/miracl_connect_label_graph_proj_dens.py", line 18, in <module>
    from allensdk.core.mouse_connectivity_cache import MouseConnectivityCache
  File "/opt/miniconda/lib/python3.7/site-packages/allensdk/core/__init__.py", line 37, in <module>
    from ._data_object_base.data_object import DataObject   # noqa F401
  File "/opt/miniconda/lib/python3.7/site-packages/allensdk/core/_data_object_base/data_object.py", line 6, in <module>
    from allensdk.brain_observatory.comparison_utils import compare_fields
  File "/opt/miniconda/lib/python3.7/site-packages/allensdk/brain_observatory/comparison_utils.py", line 5, in <module>
    import SimpleITK as sitk
  File "/opt/miniconda/lib/python3.7/site-packages/SimpleITK/__init__.py", line 18, in <module>
    from SimpleITK.SimpleITK import *
  File "/opt/miniconda/lib/python3.7/site-packages/SimpleITK/SimpleITK.py", line 10, in <module>
    from . import _SimpleITK
ImportError: /opt/miniconda/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/miniconda/lib/python3.7/site-packages/SimpleITK/_SimpleITK.so)
```

FYI, I'm using Ubuntu 18.04.

Thank you,
Yeun

**Comment by jono3030** [comment]
Hi Yeun,

Thank you very much for using MIRACL and for opening an issue!

We are currently working on a major update to MIRACL that is scheduled to be released next month. The update will introduce a number of new features and also fix some known issues including this one (related to #93).

We strongly recommend to wait for this release before using MIRACL. However, if you want to use MIRACL in the meantime, you can do the following:

1. I addressed the issue you are experiencing in a separate development branch which you can download with: `git clone --branch jo-dependencies_fix https://github.com/AICONSlab/MIRACL.git MIRACL_pre_release`
2. This will create a folder called `MIRACL_pre_release` on your system and clone the MIRACL repository into it.
3. After entering the folder you should check if you are on the correct branch (`git branch`).
4. Use the `./build.sh` script like you did the first time to build the container.
5. Once instantiated and attached to the MIRACL Docker container run `miracl -h` to test if everything is working.

I hope this helps but again, this will not be an issue in the new release. In the meantime, let us know if you run into any problems with this quick-fix.
